Update 4-empty

diff --git a/shell_permissions/4-empty b/shell_permissions/4-empty
--- a/shell_permissions/4-empty
+++ b/shell_permissions/4-empty
@@ -1,2 +1,2 @@
-#!/bin/bash
-touch hello if [ $? -eq 0 ] then echo "File 'hello' created successfully!" else echo "Error creating file 'hello'." fi
+#!/bin/bash touch hello if [ $? -eq 0 ] then echo "File 'hello' created successfully!" else echo "Error creating file 'hello'."
+fi
