Update 4-empty

diff --git a/shell_permissions/4-empty b/shell_permissions/4-empty
--- a/shell_permissions/4-empty
+++ b/shell_permissions/4-empty
@@ -1,7 +1,2 @@
 #!/bin/bash
-touch hello
-if [ $? -eq 0 ]
-then
-    echo "File 'hello' created successfully!"
-fi
-[ $? -ne 0 ] && echo "Error creating file 'hello'."
+touch hello if [ $? -eq 0 ] then; echo "File 'hello' created successfully!"; fi [ $? -ne 0 ]  echo "Error creating file 'hello'."
