Update 4-empty

diff --git a/shell_permissions/4-empty b/shell_permissions/4-empty
--- a/shell_permissions/4-empty
+++ b/shell_permissions/4-empty
@@ -1,9 +1,2 @@
-#!/bin/bash
-# Create the file "hello"
-touch hello
-# Check if the file creation was successful
-if [ $? -eq 0 ]; then
-  echo "File 'hello' created successfully!"
-else
-  echo "Error creating file 'hello'."
+#!/bin/bash touch hello; if [ $? -eq 0 ]; then echo "File 'hello' created successfully!"; else echo "Error creating file 'hello'.";
 fi
